#创建类型为headless的service资源对象
---
apiVersion: v1
kind: Service
metadata:
  name: docker-image-gossip-headless-service
  namespace: share-components
spec:
  selector:
    app: docker-image-gossip-daemon
  clusterIP: None